[build]
  command = "npm install && npm run build:css && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.2"
  NODE_VERSION = "18"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 